/**
 * @file routes-integration.test.ts
 * @description Integration tests for endpoints generated by express-mongo-gridfs router factory.
 *
 * This test suite validates the complete file management API built with the library,
 * including upload, listing, metadata retrieval, download, update, bulk operations,
 * and deletion.
 *
 * It uses an in‑memory MongoDB instance to ensure isolation and reproducibility.
 *
 * ### Prerequisites
 * - Install dev dependencies: jest, @types/jest, ts-jest, supertest, @types/supertest,
 *   mongodb-memory-server, @types/node, typescript
 * - Configure Jest with ts-jest preset
 * - Ensure the library is built before running tests (or import from source with ts-node)
 *
 * ### Run command
 *  npm test -- --testPathPattern=routes-integration.test
 */

import request from 'supertest';
import mongoose, { Model } from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import express, { Express, Request, Response, NextFunction } from 'express';
import multer from 'multer';

// Import library functions – adjust path as needed (use compiled output or source)
import {
  initGridFS,
  createFilesModel,
  createFileRouter,
  deleteFiles,
} from '../../index'; // or '../src' if testing directly

// In‑memory MongoDB instance
let mongoServer: MongoMemoryServer;
// Express app and server
let app: Express;
let server: ReturnType<Express['listen']>;
// Model instance
let FileModel: Model<any>;
// Track created file IDs for cleanup
const createdFileIds: string[] = [];

// Dummy authentication middleware – expects token in 'Authorization' header
const TEST_TOKEN = 'test-api-key';
const AUTH_USER_ID = 'test_user_123';

const authMiddleware = (req: Request, res: Response, next: NextFunction) => {
  const token = req.headers.authorization;
  if (token === TEST_TOKEN) {
    (req as any).user = { id: AUTH_USER_ID };
    return next();
  }
  res.status(401).json({ error: 'Unauthorized' });
};

// Helper: wait for GridFS to be ready (optional, initGridFS is synchronous but bucket may be lazy)
const waitForGridFS = (timeoutMs = 5000): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, 500));

beforeAll(async () => {
  // 1. Start in‑memory MongoDB
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();

  // 2. Connect Mongoose
  await mongoose.connect(uri);
  console.log('✅ Connected to test DB');

  // 3. Initialize GridFS
  initGridFS(mongoose.connection);
  await waitForGridFS();

  // 4. Create a test model with custom fields
  FileModel = createFilesModel({
    collection: 'test_files',
    modelSchema: {
      uploadedBy: { type: String, required: true },
      category: { type: String, enum: ['test', 'temp'], default: 'test' },
    },
    schemaOptions: {
      timestamps: true,
    },
  });

  // 5. Build Express app with the router
  app = express();
  app.use(express.json());

  // Create the router with our model and authentication
  const fileRouter = createFileRouter({
    model: FileModel,
    multerConfig: {
      storage: multer.memoryStorage(),
      limits: {
        fileSize: 5 * 1024 * 1024, // 5MB for tests
        files: 5,
      },
      fileFilter: (req: any, file: any, cb: any) => {
        const allowedMimes = ['image/jpeg', 'image/png', 'application/pdf'];
        if (allowedMimes.includes(file.mimetype)) {
          cb(null, true);
        } else {
          cb(new Error('Invalid file type'), false);
        }
      },
    },
    routeMiddlewares: {
      upload: [authMiddleware],
      list: [authMiddleware],
      get: [authMiddleware],
      download: [authMiddleware],
      update: [authMiddleware],
      bulkUpload: [authMiddleware],
      delete: [authMiddleware],
      deleteBulk: [authMiddleware],
    },
    swaggerConfig: {
      tags: ['Test Files'],
    },
  });

  app.use('/api/files', fileRouter);

  // 6. Start server
  server = app.listen(0);
}, 30000);

afterAll(async () => {
  // Clean up all tracked files
  for (const fileId of createdFileIds) {
    try {
      await deleteFiles(FileModel, fileId);
    } catch (err) {
      // File might already be deleted
    }
  }

  // Disconnect and stop MongoDB
  await mongoose.disconnect();
  await mongoServer.stop();

  // Close server
  if (server) {
    await new Promise<void>((resolve) => server.close(() => resolve()));
  }
});

// Helper: create a test buffer with unique content
const createTestBuffer = (prefix: string = 'test'): Buffer =>
  Buffer.from(`${prefix}_content_${Date.now()}_${Math.random()}`);

describe('File API (express-mongo-gridfs router)', () => {
  const testPrefix = `test_${Date.now()}`;

  describe('POST /api/files/upload', () => {
    it('should upload a single PDF file', async () => {
      const buffer = createTestBuffer('pdf');
      const filename = `${testPrefix}_upload.pdf`;

      const res = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .field('category', 'test')
        .attach('file', buffer, { filename, contentType: 'application/pdf' });

      expect(res.statusCode).toBe(201);
      expect(res.body.success).toBe(true);
      expect(res.body.fileId).toBeDefined();
      expect(res.body.filename).toBe(filename);
      expect(res.body.contentType).toBe('application/pdf');
      expect(res.body.length).toBe(buffer.length);
      expect(res.body.metadata.uploadedBy).toBe(AUTH_USER_ID);
      expect(res.body.metadata.category).toBe('test');

      createdFileIds.push(res.body.fileId);
    });

    it('should return 400 when no file is attached', async () => {
      const res = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .send({});

      expect(res.statusCode).toBe(400);
      expect(res.body.error).toBe('No file uploaded');
      expect(res.body.code).toBe('NO_FILE');
    });

    it('should reject a disallowed file type (e.g., ZIP)', async () => {
      const buffer = createTestBuffer('zip');
      const filename = `${testPrefix}_rejected.zip`;

      const res = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .attach('file', buffer, { filename, contentType: 'application/zip' });

      // Multer fileFilter throws error which propagates to Express error handler -> 500
      expect(res.statusCode).toBe(500);
    });

    it('should return 401 without authentication', async () => {
      const buffer = createTestBuffer('noauth');
      const res = await request(app)
        .post('/api/files/upload')
        .attach('file', buffer, { filename: 'noauth.pdf', contentType: 'application/pdf' });

      expect(res.statusCode).toBe(401);
    });
  });

  describe('GET /api/files', () => {
    it('should list files with pagination', async () => {
      // Upload a file to ensure at least one exists
      const buffer = createTestBuffer('list');
      const filename = `${testPrefix}_list.pdf`;
      const uploadRes = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', buffer, { filename, contentType: 'application/pdf' });
      expect(uploadRes.statusCode).toBe(201);
      createdFileIds.push(uploadRes.body.fileId);

      const listRes = await request(app)
        .get('/api/files')
        .set('Authorization', TEST_TOKEN)
        .query({ filename: testPrefix, page: 1, limit: 10 });

      expect(listRes.statusCode).toBe(200);
      expect(listRes.body.success).toBe(true);
      expect(Array.isArray(listRes.body.files)).toBe(true);
      expect(listRes.body.pagination).toBeDefined();
      expect(listRes.body.pagination.page).toBe(1);
      expect(listRes.body.pagination.limit).toBe(10);
      expect(typeof listRes.body.pagination.total).toBe('number');

      const found = listRes.body.files.find((f: any) => f.filename === filename);
      expect(found).toBeDefined();
    });

    it('should filter files by contentType', async () => {
      const res = await request(app)
        .get('/api/files')
        .set('Authorization', TEST_TOKEN)
        .query({ filename: testPrefix, contentType: 'pdf' });

      expect(res.statusCode).toBe(200);
      if (res.body.files.length > 0) {
        res.body.files.forEach((file: any) => {
          expect(file.contentType).toContain('pdf');
        });
      }
    });
  });

  describe('GET /api/files/:fileId', () => {
    let fileId: string;

    beforeAll(async () => {
      const buffer = createTestBuffer('metadata');
      const filename = `${testPrefix}_metadata.pdf`;
      const uploadRes = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', buffer, { filename, contentType: 'application/pdf' });
      expect(uploadRes.statusCode).toBe(201);
      fileId = uploadRes.body.fileId;
      createdFileIds.push(fileId);
    });

    it('should return metadata for an existing file', async () => {
      const res = await request(app)
        .get(`/api/files/${fileId}`)
        .set('Authorization', TEST_TOKEN);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.file._id).toBe(fileId);
      expect(res.body.file.filename).toMatch(`${testPrefix}_metadata.pdf`);
    });

    it('should return 404 for a non‑existent file', async () => {
      const fakeId = new mongoose.Types.ObjectId();
      const res = await request(app)
        .get(`/api/files/${fakeId}`)
        .set('Authorization', TEST_TOKEN);

      expect(res.statusCode).toBe(404);
      expect(res.body.error).toBe('File not found');
    });
  });

  describe('GET /api/files/download/:fileId', () => {
    let fileId: string;
    let originalBuffer: Buffer;

    beforeAll(async () => {
      originalBuffer = createTestBuffer('download');
      const filename = `${testPrefix}_download.pdf`;
      const uploadRes = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', originalBuffer, { filename, contentType: 'application/pdf' });
      expect(uploadRes.statusCode).toBe(201);
      fileId = uploadRes.body.fileId;
      createdFileIds.push(fileId);
    });

    it('should download the exact binary content', async () => {
      const res = await request(app)
        .get(`/api/files/download/${fileId}`)
        .set('Authorization', TEST_TOKEN)
        .buffer(true)
        .parse((res, cb) => {
          const chunks: Buffer[] = [];
          res.on('data', (chunk) => chunks.push(chunk));
          res.on('end', () => cb(null, Buffer.concat(chunks)));
        });

      expect(res.statusCode).toBe(200);
      expect(res.headers['content-type']).toBe('application/pdf');
      expect(Buffer.isBuffer(res.body)).toBe(true);
      expect(res.body.length).toBe(originalBuffer.length);
      expect(Buffer.compare(res.body, originalBuffer)).toBe(0);
    });

    it('should return 404 for a non‑existent file', async () => {
      const fakeId = new mongoose.Types.ObjectId();
      const res = await request(app)
        .get(`/api/files/download/${fakeId}`)
        .set('Authorization', TEST_TOKEN);

      expect(res.statusCode).toBe(404);
      expect(res.body.error).toBe('File not found');
    });

    it('should return 400 for an invalid ObjectId', async () => {
      const res = await request(app)
        .get('/api/files/download/invalid-id')
        .set('Authorization', TEST_TOKEN);

      expect(res.statusCode).toBe(400);
      expect(res.body.error).toBe('Invalid file ID format');
    });
  });

  describe('POST /api/files/update/:fileId', () => {
    let oldFileId: string;

    beforeAll(async () => {
      const buffer = createTestBuffer('old');
      const filename = `${testPrefix}_old.pdf`;
      const uploadRes = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', buffer, { filename, contentType: 'application/pdf' });
      expect(uploadRes.statusCode).toBe(201);
      oldFileId = uploadRes.body.fileId;
      createdFileIds.push(oldFileId);
    });

    it('should replace the file with a new one', async () => {
      const newBuffer = createTestBuffer('new');
      const newFilename = `${testPrefix}_new.pdf`;

      const updateRes = await request(app)
        .post(`/api/files/update/${oldFileId}`)
        .set('Authorization', TEST_TOKEN)
        .attach('file', newBuffer, { filename: newFilename, contentType: 'application/pdf' });

      expect(updateRes.statusCode).toBe(200);
      expect(updateRes.body.success).toBe(true);
      expect(updateRes.body.message).toBe('File updated successfully');
      expect(updateRes.body.oldFileId).toBe(oldFileId);
      expect(updateRes.body.newFile).toBeDefined();
      expect(updateRes.body.newFile.fileId).not.toBe(oldFileId);
      expect(updateRes.body.newFile.filename).toBe(newFilename);

      createdFileIds.push(updateRes.body.newFile.fileId);

      // Verify old file is gone
      const oldFile = await FileModel.findById(oldFileId);
      expect(oldFile).toBeNull();
    });

    it('should return 404 when updating a non‑existent file', async () => {
      const fakeId = new mongoose.Types.ObjectId();
      const buffer = createTestBuffer('nonexistent');
      const res = await request(app)
        .post(`/api/files/update/${fakeId}`)
        .set('Authorization', TEST_TOKEN)
        .attach('file', buffer, { filename: 'dummy.pdf', contentType: 'application/pdf' });

      expect(res.statusCode).toBe(404);
      expect(res.body.error).toBe('Old file not found');
    });

    it('should return 400 when no file is attached', async () => {
      const res = await request(app)
        .post(`/api/files/update/${oldFileId}`)
        .set('Authorization', TEST_TOKEN)
        .send({});

      expect(res.statusCode).toBe(400);
      expect(res.body.error).toBe('No file uploaded');
    });
  });

  describe('POST /api/files/upload-files', () => {
    it('should upload multiple files at once', async () => {
      const buffer1 = createTestBuffer('bulk1');
      const buffer2 = createTestBuffer('bulk2');

      const res = await request(app)
        .post('/api/files/upload-files')
        .set('Authorization', TEST_TOKEN)
        .attach('files', buffer1, { filename: `${testPrefix}_bulk1.pdf`, contentType: 'application/pdf' })
        .attach('files', buffer2, { filename: `${testPrefix}_bulk2.png`, contentType: 'image/png' });

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.summary.total).toBe(2);
      expect(res.body.summary.successful).toBe(2);
      expect(res.body.summary.failed).toBe(0);

      if (res.body.results) {
        res.body.results.forEach((result: any) => {
          createdFileIds.push(result.fileId);
        });
      }
    });

    it('should return 400 when no files are attached', async () => {
      const res = await request(app)
        .post('/api/files/upload-files')
        .set('Authorization', TEST_TOKEN)
        .send({});

      expect(res.statusCode).toBe(400);
      expect(res.body.error).toBe('No files uploaded');
    });
  });

  describe('DELETE /api/files/delete/:fileId', () => {
    let fileId: string;

    beforeAll(async () => {
      const buffer = createTestBuffer('delete');
      const filename = `${testPrefix}_delete.pdf`;
      const uploadRes = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', buffer, { filename, contentType: 'application/pdf' });
      expect(uploadRes.statusCode).toBe(201);
      fileId = uploadRes.body.fileId;
      createdFileIds.push(fileId);
    });

    it('should delete the file', async () => {
      const res = await request(app)
        .delete(`/api/files/delete/${fileId}`)
        .set('Authorization', TEST_TOKEN);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.message).toBe('File deleted successfully');

      const deletedFile = await FileModel.findById(fileId);
      expect(deletedFile).toBeNull();
    });

    it('should return 404 for a non‑existent file', async () => {
      const fakeId = new mongoose.Types.ObjectId();
      const res = await request(app)
        .delete(`/api/files/delete/${fakeId}`)
        .set('Authorization', TEST_TOKEN);

      expect(res.statusCode).toBe(404);
      expect(res.body.error).toBe('File not found');
    });
  });

  describe('DELETE /api/files/delete-files', () => {
    let fileId1: string, fileId2: string;

    beforeAll(async () => {
      const buffer1 = createTestBuffer('bulkdel1');
      const buffer2 = createTestBuffer('bulkdel2');
      const upload1 = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', buffer1, { filename: `${testPrefix}_bulkdel1.pdf`, contentType: 'application/pdf' });
      const upload2 = await request(app)
        .post('/api/files/upload')
        .set('Authorization', TEST_TOKEN)
        .field('uploadedBy', AUTH_USER_ID)
        .attach('file', buffer2, { filename: `${testPrefix}_bulkdel2.pdf`, contentType: 'application/pdf' });
      expect(upload1.statusCode).toBe(201);
      expect(upload2.statusCode).toBe(201);
      fileId1 = upload1.body.fileId;
      fileId2 = upload2.body.fileId;
      createdFileIds.push(fileId1, fileId2);
    });

    it('should delete multiple files by IDs', async () => {
      const res = await request(app)
        .delete('/api/files/delete-files')
        .set('Authorization', TEST_TOKEN)
        .send({ ids: [fileId1, fileId2] });

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.summary.deleted).toBe(2);
      expect(res.body.summary.failed).toBe(0);
    });

    it('should return 400 when no IDs are provided', async () => {
      const res = await request(app)
        .delete('/api/files/delete-files')
        .set('Authorization', TEST_TOKEN)
        .send({});

      expect(res.statusCode).toBe(400);
      expect(res.body.error).toBe('No file IDs provided');
    });

    it('should return 400 when all IDs are invalid', async () => {
      const res = await request(app)
        .delete('/api/files/delete-files')
        .set('Authorization', TEST_TOKEN)
        .send({ ids: ['invalid', 'garbage'] });

      expect(res.statusCode).toBe(400);
      expect(res.body.error).toBe('No valid file IDs provided');
    });
  });
});